
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fib <- function(n) { #closed form
  a <- (1+sqrt(5))/2
  b <- (1-sqrt(5))/2
  (a^n-b^n)/sqrt(5)
}

maxNr <- sum(fib(1:100)<4*10^6) #find the largest term not exceeding 4 million
sum(fib(1:maxNr)*fib(1:maxNr)%%2) #remove odd numbers with the help of modulus, then sum the numbers

