#problem 12
#The sequence of triangle numbers is generated by adding the natural numbers. 
#So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...


#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?




#create set of triangle numbers
N <- 10^5
TN <- 1
for (i in 1:N)
TN <- append(TN,TN[i]+i+1)

#find divisors

for (i in 1:10^6){
  N <- TN[i]
  divs <- 2
  for (n in 2:ceiling(N/2)){
    if (N %% n == 0) divs <- divs + 1
  }
  if (divs > 500 ){
    cat(TN[i],i,divs)
    stop("Finished")
  }
}



for (i in 1:10^6)
  if (numdivs(TN[i])>500) {
    cat(TN[i],i,numdivs(TN[i]))
    stop("Found")
  }
  
