#Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
  
#2^2=4,2^3=8, 2^4=16, 2^5=32
#32=9,33=27, 34=81, 35=243
#42=16,43=64, 44=256, 45=1024
#52=25,53=125, 54=625, 55=3125


#f they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
  
#  4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

#How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b<= 100?

res <- NULL
for (i in 2:100)
  res <- append(res,(2:100)^i)
length(unique(res))

res <- as.bigz(NULL)
for (i in 2:100)
  for (j in 2:100)
    if (!(as.bigz(i)^j %in% res)) res <- append(res,as.bigz(i)^j)


length(unique(c(outer(2:100, 2:100, FUN='^'))))
       

# From the manual
x <- seq(-10, 10, length=50)
y <- x
f <- function(x,y) {
  r <- sqrt(x^2+y^2)
  10 * sin(r)/r
}
z <- outer(x, y, f)
z[is.na(z)] <- 1
persp(x, y, z, theta = 30, phi = 30, expand = 0.5, col = "lightblue",
      shade=.5,
      xlab = "X", ylab = "Y", zlab = "Z")

# From the manual
data(volcano)
z <- 2 * volcano        # Exaggerate the relief
x <- 10 * (1:nrow(z))   # 10-meter spacing (S to N)
y <- 10 * (1:ncol(z))   # 10-meter spacing (E to W)
persp(x, y, z, 
      theta = 120, phi = 15, 
      scale = FALSE, axes = FALSE)
# See also the other examples in ?
#   demo(persp)

data(iris)
print(cloud(Sepal.Length ~ Petal.Length * Petal.Width,
            data = iris, cex = .8,
            groups = Species,
            subpanel = panel.superpose,
            main = "Stereo",
            screen = list(z = 20, x = -70, y = 3)),
      split = c(1,1,2,1), more = TRUE)
print(cloud(Sepal.Length ~ Petal.Length * Petal.Width,
            data = iris, cex = .8,
            groups = Species,
            subpanel = panel.superpose,
            main = "Stereo",
            screen = list(z = 20, x = -70, y = 0)),
      split = c(2,1,2,1))